#!/usr/bin/env bash
#Author: Alex Gabriel <alex.gabriel@microfocus.com>
#Created: 04-Feb-2020
#Modified: 20-May-2020
#Description: Short shell script that allows users to pull the most common ADM solutions when preparing for a demo.
#License: GPL 3.0

echo ""
echo "This is a short shell script that lets you pull the most common ADM containers from the admpresales Docker repository. If you have suggestions for improvement, please contact me by emailing alex.gabriel@microfocus.com"
echo ""
echo "A valid Docker login is required for this script to run properly."
echo ""

if docker login; then
	sleep 1
	else
		docker login
	fi

source functions

options[0]="Autopass"
options[1]="ALM"
options[2]="ALM Octane"
options[3]="AOS"
options[4]="AOS-QA"
options[5]="DA"
options[6]="DevOps"
options[7]="Fortify"
options[8]="IntelliJ"
options[9]="JIRA"
options[10]="LeanFT Chrome"
options[11]="MF Connect"
options[12]="PPM"
options[13]="RPA"
options[14]="Sonarqube"
options[15]="SV"
options[16]="UFT Mobile"
options[17]="All (Resource intensive)"

#Actions to take based on selection
function ACTIONS {
	if [[ ${choices[0]} ]]; then
		pull autopass ${AutopassVersion}
	fi
	if [[ ${choices[1]} ]]; then
		pull alm ${ALMVersion}
	fi
	if [[ ${choices[2]} ]]; then
		pull octane ${ALMOctaneVersion}
	fi
	if [[ ${choices[3]} ]]; then
		pull aos ${AOSVersion}
	fi
	if [[ ${choices[4]} ]]; then
		pull aos-qa ${AOSQAVersion}
	fi
	if [[ ${choices[5]} ]]; then
		pull da ${DAVersion}
	fi
	if [[ ${choices[6]} ]]; then
		pull devops ${DevOpsVersion}
	fi
	if [[ ${choices[7]} ]]; then
		pull sca ${SCAVersion}
		pull ssc ${SSCVersion}
	fi
	if [[ ${choices[8]} ]]; then
		pull intellij ${IntelliJVersion}
	fi
	if [[ ${choices[9]} ]]; then
		pull jira ${JIRAVersion}
	fi
	if [[ ${choices[10]} ]]; then
		pull leanft-chrome ${LFTChromeVersion}
	fi
	if [[ ${choices[11]} ]]; then
		pull mfconnect ${MFConnectVersion}
	fi
	if [[ ${choices[12]} ]]; then
		pull ppm ${PPMVersion}
	fi
	if [[ ${choices[13]} ]]; then
		pull rpa ${RPAVersion}
	fi
	if [[ ${choices[14]} ]]; then
		pull sonarqube ${SonarqubeVersion}
	fi
	if [[ ${choices[15]} ]]; then
		pull sv ${SVVersion}
	fi
	if [[ ${choices[16]} ]]; then
		pull uft-mobile ${UFTMVersion}
	fi
	if [[ ${choices[17]} ]]; then
		pull autopass ${AutopassVersion}
		pull alm ${ALMVersion}
		pull octane ${ALMOctaneVersion}
		pull aos ${AOSVersion}
		pull aos-qa ${AOSQAVersion}
		pull da ${DAVersion}
		pull devops ${DevOpsVersion}
		pull sca ${SCAVersion}
		pull ssc ${SSCVersion}
		pull intellij ${IntelliJVersion}
		pull jira ${JIRAVersion}
		pull leanft-chrome ${LFTChromeVersion}
		pull mfconnect ${MFConnectVersion}
		pull ppm ${PPMVersion}
		pull rpa ${RPAVersion}
		pull sonarqube ${SonarqubeVersion}
		pull sv ${SVVersion}
		pull uft-mobile ${UFTMVersion}
	fi
}

#Variables
ERROR=" "

#Clear screen for menu
#clear

#Menu function
function MENU {

	for NUM in "${!options[@]}"; do
		echo "[""${choices[NUM]:- }""]" $(( NUM+1 ))") ${options[NUM]}"
	done
	echo "$ERROR"
}

#Menu loop
while MENU && read -e -r -p "Select the desired container using its number (enter the same number to uncheck). Press enter after items 1-9, and press enter when all containers have been selected to pull them: " -n2 SELECTION && [[ -n "$SELECTION" ]]; do
	clear
	if [[ "$SELECTION" == *[[:digit:]]* && $SELECTION -ge 1 && $SELECTION -le ${#options[@]} ]]; then
		(( SELECTION-- ))
		if [[ "${choices[SELECTION]}" == "+" ]]; then
			choices[SELECTION]=""
		else
			 choices[SELECTION]="+"
		fi
			ERROR=" "
	else
		ERROR="Invalid option: $SELECTION"
	fi
done

ACTIONS