#!/bin/bash
#Author: Alex Gabriel <alex.gabriel@microfocus.com>
#Created: 04/02/2020
#Modified: 08/032020
#Description: Short shell script that allows users to pull the most common ADM solutions when preparing for a demo.
#License: GPL 3.0

echo ""
echo "This is a short shell script that lets you pull the most common ADM containers from the admpresales Docker repository. If you have suggestions for improvement, please contact me by emailing alex.gabriel@microfocus.com"
echo ""
echo "A valid Docker login is required for this script to run properly."
echo ""
source functions
docker login
echo ""
PS3='Select the container(s) to pull, or 19 to quit. '
options=("Autopass" "ALM Octane" "ALM" "AOS" "AOS-QA" "DA" "DevOps" "Fortify" "IntelliJ" "JIRA" "LeanFT-Chrome" "MF Connect" "PPM" "RPA" "Sonarqube" "SV" "UFT Mobile" "All" "Quit")
select opt in "${options[@]}"; do
     case ${opt} in
          "Autopass")
               pullAutopass
               ;;
          "ALM")
               pullALM
               ;;
          "ALM Octane")
               pullALMOctane
               ;;
          "AOS")
               pullAOS
               ;;
          "AOS-QA")
               pullAOSQA
               ;;
          "DA")
               pullDA
               ;;
          "DevOps")
               pullDevOps
               ;;
          "Fortify")
               pullFortify
               ;;
          "IntelliJ")
               pullIntelliJ
               ;;
          "JIRA")
               pullJIRA
               ;;
          "LeanFT-Chrome")
               pullLFTChrome
               ;;
          "MF Connect")
               pullMFConnect
               ;;
          "PPM")
               pullPPM
               ;;
          "RPA")
               pullRPA
               ;;
          "Sonarqube")
               pullSonarqube
               ;;
          "SV")
               pullSV
               ;;
          "UFT Mobile")
               pullUFTM
               ;;
          "All")
               pullALM
               pullALMOctane
               pullAOS
               pullAOSQA
               pullAutopass
               pullDA
               pullDevOps
               pullFortify
               pullIntelliJ
               pullJIRA
               pullLFTChrome
               pullMFConnect
               pullPPM
               pullRPA
               pullSV
               pullSonarqube
               pullUFTM
               continue
               ;;
          "Quit")
               exit
               ;;
          *) echo "Invalid option $REPLY" ;;
     esac
done
