#!/bin/bash
#Author: Alex Gabriel <alex.gabriel@microfocus.com>
#Created: 21/02/2020
#Modified: 21/02/2020
#Description: Short shell script that allows users to restart the most common ADM solutions when preparing for a demo.
#License: GPL 3.0

echo ""
echo "This is a short shell script that lets you restart the most common ADM containers. If the container is running, a message is displayed.  If you have suggestions for improvement, please contact me by emailing alex.gabriel@microfocus.com"
echo ""
include functions
PS3='Select the container(s) to restart, or 13 to quit. '
options=("Autopass" "ALM" "ALM Octane" "AOS" "DA" "DevOps" "Fortify" "IntelliJ" "MF Connect" "SV" "UFT Mobile" "All" "Quit")
select opt in "${options[@]}"; do
  case $opt in
  "Autopass")
    restartAutopass
    ;;
  "ALM")
    restartALM
    ;;
  "ALM Octane")
    restartALMOctane
    ;;
  "AOS")
    restartAOS
    ;;
  "DA")
    restartDA
    ;;
  "DevOps")
    restartDevOps
    ;;
  "Fortify")
    restartFortify
    continue
    ;;
  "IntelliJ")
    restartIntelliJ
    continue
    ;;
  "MF Connect")
    restartMFConnect
    continue
    ;;
  "SV")
    restartSV
    continue
    ;;
  "UFT Mobile")
    restartUFTM
    continue
    ;;
"All")
    restartAutopass
    restartALM
    restartALMOctane
    restartAOS
    restartDA
    restartDevOps
    restartFortify
    restartIntelliJ
    restartMFConnect
    restartSV
    restartUFTM
    continue
    ;;
  "Quit")
    exit
    ;;
  *) echo "Invalid option $REPLY" ;;
  esac
done
