#!/bin/bash
#Author: Alex Gabriel <alex.gabriel@microfocus.com>
#Created: 04/02/2020
#Modified: 28/02/2020
#Description: Short shell script that allows users to stop the most common ADM solutions when preparing for a demo.
#License: GPL 3.0

echo ""
echo "This is a short shell script that lets you stop the most common ADM containers. If you have suggestions for improvement, please contact me by emailing alex.gabriel@microfocus.com"
echo ""
source functions
PS3='Select the container(s) to stop, or 14 to quit. '
options=("Autopass" "ALM" "ALM Octane" "AOS" "DA" "DevOps" "Fortify" "IntelliJ" "JIRA" "MF Connect" "SV" "UFT Mobile" "All" "Quit")
select opt in "${options[@]}"; do
  case $opt in
  "Autopass")
    stopAutopass
    ;;
  "ALM")
    stopALM
    ;;
  "ALM Octane")
    stopALMOctane
    ;;
  "AOS")
    stopAOS
    ;;
  "DA")
    stopDA
    ;;
  "DevOps")
    stopDevOps
    ;;
  "Fortify")
    stopFortify
    continue
    ;;
  "IntelliJ")
    stopIntelliJ
    continue
    ;;
  "JIRA")
    startJIRA
    continue
    ;;
  "MF Connect")
    stopMFConnect
    continue
    ;;
  "SV")
    stopSV
    continue
    ;;
  "UFT Mobile")
    stopUFTM
    continue
    ;;
  "All")
    stopUFTM
    stopSV
    stopMFConnect
    stopIntelliJ
    stopJIRA
    stopFortify
    stopDevOps
    stopDA
    stopAOS
    stopALMOctane
    stopALM
    stopAutopass
    continue
    ;;
  "Quit")
    exit
    ;;
  *) echo "Invalid option $REPLY" ;;
  esac
done
