#!/bin/bash
#Author: Alex Gabriel <alex.gabriel@microfocus.com>
#Created: 04/02/2020
#Modified: 08/03/2020
#Description: Short shell script that allows users to start the most common ADM solutions when preparing for a demo.
#License: GPL 3.0

echo ""
echo "This is a short shell script that lets you start the most common ADM containers from the admpresales Docker repository. If the containers do not exist, they will be pulled first, and then started.  If you have suggestions for improvement, please contact me by emailing alex.gabriel@microfocus.com"
echo ""
source functions
docker login
PS3='Select the container(s) to start, or 19 to quit. '
options=("Autopass" "ALM Octane" "ALM" "AOS" "AOS-QA" "DA" "DevOps" "Fortify" "IntelliJ" "JIRA" "LeanFT-Chrome" "MF Connect" "PPM" "RPA" "Sonarqube" "SV" "UFT Mobile" "All" "Quit")
select opt in "${options[@]}"; do
     case ${opt} in
          "Autopass")
               startAutopass
               ;;
          "ALM")
               startALM
               ;;
          "ALM Octane")
               startALMOctane
               ;;
          "AOS")
               startAOS
               ;;
          "AOS-QA")
               startAOSQA
               ;;
          "DA")
               startDA
               ;;
          "DevOps")
               startDevOps
               ;;
          "Fortify")
               startFortify
               ;;
          "IntelliJ")
               startIntelliJ
               ;;
          "JIRA")
               startJIRA
               ;;
          "LeanFT-Chrome")
               startLFTChrome
               ;;
          "MF Connect")
               startMFConnect
               ;;
          "PPM")
               startPPM
               ;;
          "RPA")
               startRPA
               ;;
          "Sonarqube")
               startSonarqube
               ;;
          "SV")
               startSV
               ;;
          "UFT Mobile")
               startUFTM
               ;;
          "All")
               startAutopass
               startALM
               startALMOctane
               startAOS
               startAOSQA
               startDA
               startDevOps
               startFortify
               startIntelliJ
               startJIRA
               startLFTChrome
               startMFConnect
               startPPM
               startRPA
               startSV
               startSonarqube
               startUFTM
               continue
               ;;
          "Quit")
               exit
               ;;
          *) echo "Invalid option $REPLY" ;;
     esac
done
