#!/bin/bash
#Author: Alex Gabriel <alex.gabriel@microfocus.com>
#Created: 04-Feb-2020
#Modified: 17-Apr-2020
#Description: Short shell script that allows users to stop the most common ADM solutions when preparing for a demo.
#License: GPL 3.0

echo ""
echo "This is a short shell script that lets you stop the most common ADM containers. If you have suggestions for improvement, please contact me by emailing alex.gabriel@microfocus.com"
echo ""
source functions
while :
do
    cat<<EOF

    Select the container(s) to stop:

    (1) Autopass
    (2) ALM
    (3) ALM Octane
    (4) AOS
    (5) AOS-QA
    (6) DA
    (7) DevOps
    (8) Fortify
    (9) IntelliJ
    (10) JIRA
    (11) LeanFT-Chrome
    (12) MF Connect
    (13) PPM
    (14) RPA
    (15) Sonarqube
    (16) SV
    (17) UFT Mobile
    (18) All
    (Q)uit
EOF
    read
    case "$REPLY" in
    "1")  stopAutopass ;;
    "2")  stopALM ;;
    "3")  stopALMOctane ;;
    "4")  stopAOS ;;
    "5")  stopAOSQA ;;
    "6")  stopDA ;;
    "7")  stopDevOps ;;
    "8")  stopFortify ;;
    "9")  stopIntelliJ ;;
    "10")  stopJIRA ;;
    "11")  stopLFTChrome ;;
    "12")  stopMFConnect ;;
    "13")  stopPPM ;;
    "14")  stopRPA ;;
    "15")  stopSonarqube ;;
    "16")  stopSV ;;
    "17")  stopUFTMobile ;;
    "18")  stopUFTM ; stopSV ; stopSonarqube ; stopRPA ; stopPPM ; stopMFConnect ; stopLFTChrome ; stopJIRA ; stopIntelliJ ; stopFortify ; stopDevOps ; stopDA ; stopAOSQA ; stopAOS ; stopALMOctane ; stopALM ; stopAutopass ;;
    "Q")  exit ;;
    "q")  exit ;;
     * )  echo "Invalid Option" ;;
    esac
    sleep 1
done