#!/bin/bash
#Author: Alex Gabriel <alex.gabriel@microfocus.com>
#Created: 04-Feb-2020
#Modified: 16-May-2020
#Description: Short shell script that allows users to start the most common ADM solutions when preparing for a demo.
#License: GPL 3.0

ALMOctaneVersion="15.0.46.68"
ALMVersion="15.0.1"
AOSQAVersion="2.3"
AOSVersion="2.3"
AutopassVersion="10.9.2"
DAVersion="6.3.1"
DevOpsVersion="2.3.0"
IntelliJVersion="2.3.0"
JIRAVersion="8.0.2"
LFTChromeVersion="15.0"
MFConnectVersion="4.3.0"
PPMVersion="9.55"
RPAVersion="2019.11"
SCAVersion="19.2.3"
SSCVersion="19.2.0"
SVVersion="5.3"
SonarqubeVersion="7.7"
UFTMVersion="3.4"

source pullfunctions.sh
source restartfunctions.sh
source startfunctions.sh
source stopfunctions.sh